### ISSUE TITLE
Failed to create a session. Please check your internet connection and try again.

### ISSUE THREAD

**Issue by dev852com** [zercurity/zercurity#1]
Hello,

I am having issues logging in getting prompted with 'Failed to create a session. Please check your internet connection and try again.'

I have followed the readme and built it in microk8s kubectl. The only difference is using Traefik router instead of the Nginx script provided. 

Please find the image attached.

<img width="1388" alt="Screenshot 2021-11-06 at 10 26 42 PM" src="https://user-images.githubusercontent.com/88053027/140613103-8f23af97-201d-42ca-bd28-acae16306d41.png">

Plz help! Thank you.

**Comment by hughneale** [comment]
Hi @dev852com,

Just to double check you've visited `https://api.<your domain>` and `https://download.<your domain>` to accept the self-signed certificate?

H

**Comment by dev852com** [comment]
Hi @hughneale 

Thank you for your quick reply! I have made ingress for `https://api.<your domain>` and `https://download.<your domain>` but getting stuck on an infinite loop: Prompt **Token expired. Fetching new token.**

```
curl https://api.<your domain>/v1/token 
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>
```
This is only working on Nginx as intended?

**Comment by hughneale** [comment]
Hi @dev852com,

You'll get a 404 when the server_name isn't matched. What ingress system are you using and how is it configured? I'm wondering if the Host header is being passed in the nginx proxy_pass?

`proxy_set_header Host api.<your domain>;`

You can also double check that the [nginx loadbalancer](https://github.com/zercurity/zercurity/blob/main/installers/kubectl/svc-nginx.yml) service has the correct config attached.

```
kublectl -n zercurity get svc
curl -vvv -H 'Host: api.cm1.zercurity.com' https://<svc.nginx_lb>
```

H

**Comment by hughneale** [comment]
Sorry, just saw you've said you're using Traefik.

**Comment by dev852com** [comment]
Hello @hughneale,

I have resolved this by using the docker script placing in LXC docker and dynamically routing it with Traefik from kubectl. I don't think it is possible to route it directly to the frontend... With the kubectl script provided. Thank you so much for your help anyway!
